# Netlify configuration file

# This ensures that all routes are sent to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set environment variables for production
[build]
  command = "npm run build"
  publish = "dist"